### ISSUE TITLE
Division 

### ISSUE THREAD

**Issue by ActividadGrupal** [ActividadGrupal/ActividadGrupal-Calculadora#3]
Se espera el codigo de division

**Comment by QuimeyDelgado** [comment]
def suma(a, b):
    resultado = a + b
    return resultado

**Comment by QuimeyDelgado** [comment]
def division(a, b):
    if b == 0:
        print("Error: No se puede dividir entre cero")
        return None
    else:
        resultado = a / b
        return resultado
